# Generated by Django 6.1.1 on 2026-10-03 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_customermaster_user'),
        ('orders', '0002_sale_carrier_sale_customer_sale_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salepayment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='catalogue.customermaster'),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='sales_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_transactions', to='orders.salesreturn'),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns', to='catalogue.customermaster'),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='total_refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salepayment',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='orders.sale'),
        ),
    ]
