# Generated by Django 6.1.1 on 2026-10-03 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_agegroupmaster_brandmaster_designmaster_and_more'),
        ('orders', '0003_salepayment_customer_salepayment_sales_return_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PettyCashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(max_length=50, unique=True, verbose_name='Voucher Number')),
                ('transaction_type', models.CharField(choices=[('cash_in', 'Cash In (Top-Up / Deposit)'), ('cash_out', 'Cash Out (Disbursement / Expense)')], default='cash_out', max_length=20)),
                ('category', models.CharField(default='Office Supplies', max_length=100, verbose_name='Expense / Inflow Category')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payee_name', models.CharField(max_length=150, verbose_name='Payee / Recipient Name')),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Approved By')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='Remarks / Business Purpose')),
                ('transacted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Void')], db_index=True, default=1)),
            ],
            options={
                'verbose_name': 'Petty Cash Voucher',
                'verbose_name_plural': 'Petty Cash Vouchers',
                'db_table': 'petty_cash_transactions',
                'ordering': ['-transacted_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=50, unique=True, verbose_name='Receipt Number')),
                ('customer_name', models.CharField(blank=True, max_length=150, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_mode', models.CharField(default='cash', max_length=50, verbose_name='Payment Mode')),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ref / UTR / Cheque No')),
                ('receipt_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Cancelled')], db_index=True, default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_receipts', to='catalogue.customermaster')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='orders.sale')),
            ],
            options={
                'verbose_name': 'Billing Receipt',
                'verbose_name_plural': 'Billing Receipts',
                'db_table': 'billing_receipts',
                'ordering': ['-receipt_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advance_number', models.CharField(max_length=50, unique=True, verbose_name='Advance Slip Number')),
                ('customer_name', models.CharField(blank=True, max_length=150, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Advance Received')),
                ('used_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Allocated / Used Amount')),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Available Advance Balance')),
                ('payment_mode', models.CharField(default='upi', max_length=50, verbose_name='Mode of Payment')),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Transaction Ref')),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Void / Refunded')], db_index=True, default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advances', to='catalogue.customermaster')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_payments', to='orders.sale')),
            ],
            options={
                'verbose_name': 'Customer Advance',
                'verbose_name_plural': 'Customer Advances',
                'db_table': 'customer_advances',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=50, unique=True, verbose_name='Lot Number')),
                ('inward_date', models.DateField(auto_now_add=True)),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Cancelled')], db_index=True, default=1)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goods_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots', to='orders.goodsreceipt')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_lots', to='orders.supplier')),
            ],
            options={
                'verbose_name': 'Purchase Lot',
                'verbose_name_plural': 'Purchase Lots',
                'db_table': 'purchase_lots',
                'ordering': ['-created_at'],
            },
        ),
    ]
