# Generated by Django 6.1.1 on 2026-09-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('legal_name', models.CharField(max_length=255, verbose_name='Legal Registered Name')),
                ('short_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Short Name')),
                ('gst_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='GST Number / Tax ID')),
                ('address_line_1', models.CharField(max_length=255, verbose_name='Address 1')),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address 2')),
                ('area', models.CharField(blank=True, max_length=150, null=True, verbose_name='Area / Locality')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State')),
                ('country', models.CharField(default='India', max_length=100, verbose_name='Country')),
                ('pincode', models.CharField(max_length=20, verbose_name='Pincode / Postal Code')),
                ('map_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Google Map URL')),
                ('company_image', models.ImageField(blank=True, null=True, upload_to='company/images/', verbose_name='Company Image')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='company/logos/', verbose_name='Logo Image')),
                ('has_social_media', models.BooleanField(default=False, verbose_name='Social Media Available (Yes/No)')),
                ('website_url', models.URLField(blank=True, max_length=300, null=True, verbose_name='Website URL')),
                ('instagram_url', models.URLField(blank=True, max_length=300, null=True, verbose_name='Instagram URL')),
                ('youtube_url', models.URLField(blank=True, max_length=300, null=True, verbose_name='YouTube URL')),
                ('whatsapp_url', models.URLField(blank=True, max_length=300, null=True, verbose_name='WhatsApp URL / Link')),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], db_index=True, default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='GeneralSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Setting Key')),
                ('value', models.TextField(verbose_name='Setting Value')),
                ('value_type', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('boolean', 'Boolean'), ('json', 'JSON')], default='string', max_length=20)),
                ('group', models.CharField(db_index=True, default='general', help_text='e.g. currency, store, invoice, notifications', max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], db_index=True, default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'General Setting',
                'verbose_name_plural': 'General Settings',
                'db_table': 'general_settings',
                'ordering': ['group', 'key'],
            },
        ),
    ]
