# Generated by Django 6.1.1 on 2026-10-03 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Branch Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Branch Code')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=120, null=True, verbose_name='Email Address')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='State')),
                ('pincode', models.CharField(blank=True, max_length=20, null=True, verbose_name='Pincode')),
                ('gstin', models.CharField(blank=True, max_length=20, null=True, verbose_name='GSTIN')),
                ('is_head_office', models.BooleanField(default=False, verbose_name='Head Office Flag')),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], db_index=True, default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Branch Master',
                'verbose_name_plural': 'Branch Masters',
                'db_table': 'branch_masters',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Department Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Department Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], db_index=True, default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department Master',
                'verbose_name_plural': 'Department Masters',
                'db_table': 'department_masters',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Profession Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], db_index=True, default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profession Master',
                'verbose_name_plural': 'Profession Masters',
                'db_table': 'profession_masters',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DesignationMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Designation Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Designation Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], db_index=True, default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='designations', to='company.departmentmaster')),
            ],
            options={
                'verbose_name': 'Designation Master',
                'verbose_name_plural': 'Designation Masters',
                'db_table': 'designation_masters',
                'ordering': ['name'],
            },
        ),
    ]
