# Generated by Django 6.1.1 on 2026-10-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Gateway Name')),
                ('gateway_code', models.CharField(help_text='razorpay, stripe, phonepe, paytm, cashfree', max_length=50, unique=True, verbose_name='Gateway Code')),
                ('api_key', models.CharField(max_length=255, verbose_name='API Key / Client ID')),
                ('api_secret', models.CharField(max_length=255, verbose_name='API Secret Key')),
                ('webhook_secret', models.CharField(blank=True, max_length=255, null=True, verbose_name='Webhook Secret')),
                ('merchant_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Merchant ID')),
                ('is_test_mode', models.BooleanField(default=True, verbose_name='Sandbox / Test Mode')),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], db_index=True, default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Gateway',
                'verbose_name_plural': 'Payment Gateways',
                'db_table': 'payment_gateway_configs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShopIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('amazon', 'Amazon Seller Central'), ('flipkart', 'Flipkart Marketplace'), ('custom', 'Custom REST API')], default='shopify', max_length=50)),
                ('store_name', models.CharField(max_length=150, verbose_name='Store / Account Name')),
                ('store_url', models.URLField(max_length=255, verbose_name='Store URL')),
                ('api_key', models.CharField(max_length=255, verbose_name='API Key / Access Token')),
                ('api_secret', models.CharField(blank=True, max_length=255, null=True, verbose_name='API Secret / Shared Key')),
                ('sync_interval_minutes', models.IntegerField(default=30, verbose_name='Sync Interval (Minutes)')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Synced At')),
                ('sync_status', models.CharField(default='idle', max_length=30, verbose_name='Current Sync Status')),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], db_index=True, default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shop Integration',
                'verbose_name_plural': 'Shop Integrations',
                'db_table': 'shop_integrations',
                'ordering': ['store_name'],
            },
        ),
    ]
