# Generated by Django 6.1.1 on 2026-10-02 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_statemaster_customermaster'),
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleschannel',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], db_index=True, default=1, help_text='1 = Active, 0 = Inactive'),
        ),
        migrations.CreateModel(
            name='ChannelListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_sku', models.CharField(db_index=True, help_text='Marketplace Seller SKU', max_length=100)),
                ('external_listing_id', models.CharField(blank=True, help_text='ASIN (Amazon) / FSN (Flipkart)', max_length=100, null=True)),
                ('listing_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Marketplace Selling Price')),
                ('sync_inventory', models.BooleanField(default=True, help_text='Auto-push live sellable stock')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(default='synced', max_length=50)),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], db_index=True, default=1, help_text='1 = Active, 0 = Inactive')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='channels.saleschannel', verbose_name='Sales Channel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_listings', to='catalogue.producttype', verbose_name='Catalogue Product')),
            ],
            options={
                'db_table': 'channel_listings',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('channel', 'channel_sku'), name='unique_channel_sku')],
            },
        ),
    ]
