# Generated by Django 6.1.1 on 2026-10-02 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_statemaster_customermaster'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_on_hand', models.PositiveIntegerField(default=0, help_text='Total physical count')),
                ('sellable_stock', models.PositiveIntegerField(default=0, help_text='Available to Promise (Broadcast to Amazon/Flipkart)')),
                ('reserved_stock', models.PositiveIntegerField(default=0, help_text='Locked in unfulfilled orders')),
                ('approval_stock', models.PositiveIntegerField(default=0, help_text='Out on photoshoot / PR memo')),
                ('quarantine_stock', models.PositiveIntegerField(default=0, help_text='Customer returns under inspection')),
                ('repair_stock', models.PositiveIntegerField(default=0, help_text='In alteration / workshop repair')),
                ('damaged_stock', models.PositiveIntegerField(default=0, help_text='Scrap / written off')),
                ('reorder_level', models.PositiveIntegerField(default=10, help_text='Minimum safety threshold')),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], db_index=True, default=1, help_text='1 = Active, 0 = Inactive')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_stock', to='catalogue.producttype')),
            ],
            options={
                'verbose_name': 'Inventory Stock',
                'verbose_name_plural': 'Inventory Stocks',
                'db_table': 'inventory_stocks',
                'ordering': ['product_id'],
            },
        ),
        migrations.CreateModel(
            name='StockMovementLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('purchase_inward', 'Purchase / GRN Inward'), ('return_restock', 'Return Restocked after QC'), ('approval_return', 'Returned from Approval / Photoshoot'), ('repair_return', 'Returned from Repair / Alteration'), ('audit_plus', 'Stock Audit Plus Adjustment'), ('pos_sale', 'POS Billing Sale'), ('marketplace_sale', 'Marketplace Sale (Amazon/Flipkart)'), ('approval_outward', 'Sent to Photoshoot / Approval Memo'), ('repair_outward', 'Sent to Repair / Alteration Workshop'), ('vendor_return', 'Returned to Vendor (RTV)'), ('scrap_writeoff', 'Damaged / Scrap Write-Off'), ('audit_minus', 'Stock Audit Minus Adjustment')], db_index=True, max_length=30)),
                ('from_bucket', models.CharField(blank=True, max_length=20, null=True)),
                ('to_bucket', models.CharField(blank=True, max_length=20, null=True)),
                ('inward_qty', models.PositiveIntegerField(default=0)),
                ('outward_qty', models.PositiveIntegerField(default=0)),
                ('lot_number', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('item_barcode', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('reference_type', models.CharField(max_length=50)),
                ('reference_id', models.CharField(db_index=True, max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], db_index=True, default=1, help_text='1 = Active, 0 = Inactive')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_stock_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.PROTECT, related_name='ledger_movements', to='catalogue.producttype')),
            ],
            options={
                'verbose_name': 'Stock Movement Ledger',
                'verbose_name_plural': 'Stock Movement Ledgers',
                'db_table': 'stock_movement_ledger',
                'ordering': ['-created_at'],
            },
        ),
    ]
