# Generated by Django 6.1.1 on 2026-10-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorystock_stockmovementledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovementledger',
            name='reference_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='stockmovementledger',
            name='reference_type',
            field=models.CharField(blank=True, default='DIRECT', max_length=50),
        ),
    ]
