# Generated by Django 6.1.1 on 2026-10-02 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stockmovementledger_reference_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockIssueType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Issue Type Name')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Code Identifier')),
                ('deduct_from_available_stock', models.BooleanField(default=True, help_text='If True, issuing stock removes it from available stock. If False, stock remains counted as available.')),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], db_index=True, default=1, help_text='1 = Active, 0 = Inactive')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock Issue Type',
                'verbose_name_plural': 'Stock Issue Types',
                'db_table': 'stock_issue_types',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='stockmovementledger',
            name='issue_type',
            field=models.ForeignKey(blank=True, db_column='issue_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.stockissuetype', verbose_name='Stock Issue Type'),
        ),
    ]
