# Generated by Django 6.1.1 on 2026-10-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockissuetype_stockmovementledger_issue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovementledger',
            name='movement_type',
            field=models.CharField(choices=[('purchase_inward', 'Purchase / GRN Inward'), ('return_restock', 'Return Restocked after QC'), ('return_quarantine', 'Customer Return Quarantine'), ('qc_restock', 'QC Pass & Restock Return'), ('approval_return', 'Returned from Approval / Photoshoot'), ('repair_return', 'Returned from Repair / Alteration'), ('branch_transfer_inward', 'Branch Transfer Inward'), ('audit_plus', 'Stock Audit Plus Adjustment'), ('pos_sale', 'POS Billing Sale'), ('marketplace_sale', 'Marketplace Sale (Amazon/Flipkart)'), ('branch_transfer_outward', 'Branch Transfer Outward'), ('approval_outward', 'Sent to Photoshoot / Approval Memo'), ('repair_outward', 'Sent to Repair / Alteration Workshop'), ('vendor_return', 'Returned to Vendor (RTV)'), ('scrap_writeoff', 'Damaged / Scrap Write-Off'), ('audit_minus', 'Stock Audit Minus Adjustment')], db_index=True, max_length=30),
        ),
    ]
