# Generated by Django 6.1.1 on 2026-10-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_stockmovementledger_movement_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeEditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_barcode', models.CharField(db_index=True, max_length=64, verbose_name='Original Barcode')),
                ('new_barcode', models.CharField(db_index=True, max_length=64, verbose_name='New Barcode')),
                ('sku', models.CharField(blank=True, max_length=64, null=True, verbose_name='SKU')),
                ('product_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Product Name')),
                ('reason', models.TextField(verbose_name='Correction Reason')),
                ('edited_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Edited By')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Edited At')),
            ],
            options={
                'verbose_name': 'Barcode Edit Log',
                'verbose_name_plural': 'Barcode Edit Logs',
                'db_table': 'barcode_edit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DuplicateBarcodeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, max_length=64, verbose_name='Duplicate Barcode')),
                ('duplicate_count', models.PositiveIntegerField(default=2, verbose_name='Instances Detected')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Detection Point')),
                ('resolved', models.BooleanField(default=False, verbose_name='Is Resolved')),
                ('resolution_notes', models.TextField(blank=True, null=True, verbose_name='Resolution Notes')),
                ('reported_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reported By')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='Reported At')),
            ],
            options={
                'verbose_name': 'Duplicate Barcode Log',
                'verbose_name_plural': 'Duplicate Barcode Logs',
                'db_table': 'duplicate_barcode_logs',
                'ordering': ['-reported_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderBarcodeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(db_index=True, max_length=64, verbose_name='Scanned Barcode')),
                ('sku', models.CharField(blank=True, max_length=64, null=True, verbose_name='SKU')),
                ('product_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Product Name')),
                ('sale_number', models.CharField(db_index=True, max_length=64, verbose_name='Order / Sale Number')),
                ('customer_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Customer')),
                ('is_linked', models.BooleanField(default=True, verbose_name='Is Active Link')),
                ('unlink_reason', models.TextField(blank=True, null=True, verbose_name='Unlink Reason')),
                ('linked_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Linked By')),
                ('linked_at', models.DateTimeField(auto_now_add=True, verbose_name='Linked At')),
                ('unlinked_at', models.DateTimeField(blank=True, null=True, verbose_name='Unlinked At')),
            ],
            options={
                'verbose_name': 'Order Barcode Link',
                'verbose_name_plural': 'Order Barcode Links',
                'db_table': 'order_barcode_links',
                'ordering': ['-linked_at'],
            },
        ),
        migrations.CreateModel(
            name='RebarcodingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_no', models.CharField(max_length=50, verbose_name='Rebarcoding Batch')),
                ('old_barcode', models.CharField(max_length=64, verbose_name='Old Barcode')),
                ('new_barcode', models.CharField(max_length=64, verbose_name='New Generated Barcode')),
                ('sku', models.CharField(blank=True, max_length=64, null=True, verbose_name='SKU')),
                ('reason', models.CharField(default='Damaged Tag', max_length=100, verbose_name='Reason')),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Void')], db_index=True, default=1)),
                ('performed_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Staff')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Processed At')),
            ],
            options={
                'verbose_name': 'Rebarcoding Record',
                'verbose_name_plural': 'Rebarcoding Records',
                'db_table': 'rebarcoding_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
