# Generated by Django 6.1.1 on 2026-10-02 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0006_statemaster_customermaster'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inward_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='GRN / Inward Number')),
                ('invoice_number', models.CharField(max_length=100, verbose_name='Supplier Invoice / Bill No')),
                ('invoice_date', models.DateField(verbose_name='Supplier Invoice Date')),
                ('inward_date', models.DateField(auto_now_add=True, verbose_name='Inward Date')),
                ('total_taxable_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('inward_status', models.CharField(choices=[('draft', 'Draft'), ('received', 'Received / Stocked'), ('cancelled', 'Cancelled')], db_index=True, default='received', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], db_index=True, default=1, help_text='1 = Active, 0 = Inactive')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_inwards', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inwards', to='catalogue.vendormaster', verbose_name='Vendor / Supplier')),
            ],
            options={
                'verbose_name': 'Purchase Inward',
                'verbose_name_plural': 'Purchase Inwards',
                'db_table': 'purchase_inwards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InwardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Inward Quantity')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Purchase Cost Price')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='GST Rate %')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('lot_number', models.CharField(db_index=True, max_length=50, verbose_name='Batch / Lot Number')),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], db_index=True, default=1, help_text='1 = Active, 0 = Inactive')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inward_items', to='catalogue.producttype')),
                ('inward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inward.purchaseinward')),
            ],
            options={
                'verbose_name': 'Inward Item',
                'verbose_name_plural': 'Inward Items',
                'db_table': 'inward_items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TaggedInventoryUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_barcode', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='Physical Barcode Sticker')),
                ('lot_number', models.CharField(db_index=True, max_length=50)),
                ('current_bucket', models.CharField(choices=[('sellable', 'Sellable On-Hand'), ('reserved', 'Order Reserved'), ('approval', 'Approval / Photoshoot Memo'), ('quarantine', 'Customer Return Quarantine'), ('repair', 'Repair / Alteration Workshop'), ('damaged', 'Damaged / Scrap Write-Off'), ('sold', 'Sold & Dispatched')], db_index=True, default='sellable', max_length=20)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_sold', models.BooleanField(db_index=True, default=False)),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], db_index=True, default=1, help_text='1 = Active, 0 = Inactive')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inward_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_units', to='inward.inwarditem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tagged_units', to='catalogue.producttype')),
            ],
            options={
                'verbose_name': 'Tagged Inventory Unit',
                'verbose_name_plural': 'Tagged Inventory Units',
                'db_table': 'tagged_inventory_units',
                'ordering': ['id'],
            },
        ),
    ]
