# Generated by Django 6.1.2 on 2026-10-10 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0008_agegroupmaster_brandmaster_designmaster_and_more'),
        ('inward', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inwarditem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inward_items', to='catalogue.productvariant', verbose_name='Product Variant (SKU)'),
        ),
        migrations.AddField(
            model_name='taggedinventoryunit',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tagged_units', to='catalogue.productvariant', verbose_name='Product Variant (SKU)'),
        ),
    ]
