# Generated by Django 6.1.1 on 2026-09-25 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GstMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='GST Slab Name')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tax Rate (%)')),
                ('cgst_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='CGST (%)')),
                ('sgst_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='SGST (%)')),
                ('igst_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='IGST (%)')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], db_index=True, default=1, help_text='1 = Active, 0 = Inactive')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gst_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gst_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'GST Master',
                'verbose_name_plural': 'GST Masters',
                'db_table': 'gst_masters',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CategoryMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Category Name')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('hsn_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='HSN Code')),
                ('image', models.CharField(blank=True, max_length=255, null=True, verbose_name='Category Image')),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], db_index=True, default=1, help_text='1 = Active, 0 = Inactive')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_created', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategories', to='catalogue.categorymaster', verbose_name='Parent Category')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_updated', to=settings.AUTH_USER_MODEL)),
                ('tax_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tax_group', to='catalogue.gstmaster')),
            ],
            options={
                'verbose_name': 'Category Master',
                'verbose_name_plural': 'Category Masters',
                'db_table': 'category_masters',
                'ordering': ['-created_at'],
            },
        ),
    ]
