# Generated by Django 6.1.1 on 2026-09-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_producttype_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], db_index=True, default=1, help_text='1 = Active, 0 = Inactive'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], db_index=True, default=1, help_text='1 = Active, 0 = Inactive'),
        ),
    ]
