# Generated by Django 6.1.1 on 2026-09-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_producttype_status_productvariant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Retail Selling Price (M.R.P.)', max_digits=10),
        ),
    ]
