# Generated by Django 6.1.1 on 2026-09-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_producttype_selling_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Vendor / Supplier Name')),
                ('vendor_code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Vendor Code')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Person')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=120, null=True, verbose_name='Email Address')),
                ('gstin', models.CharField(blank=True, max_length=15, null=True, verbose_name='GSTIN Number')),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='PAN Number')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Street Address')),
                ('city', models.CharField(blank=True, max_length=60, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, max_length=60, null=True, verbose_name='State')),
                ('pincode', models.CharField(blank=True, max_length=10, null=True, verbose_name='PIN Code')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Name')),
                ('account_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Account Number')),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='IFSC Code')),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], db_index=True, default=1, help_text='1 = Active, 0 = Inactive')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vendor Master',
                'verbose_name_plural': 'Vendor Masters',
                'db_table': 'vendor_masters',
                'ordering': ['-created_at'],
            },
        ),
    ]
