# Generated by Django 6.1.1 on 2026-10-02 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_vendormaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. 33 for Tamil Nadu', max_length=2, unique=True, verbose_name='GST State Code')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='State / UT Name')),
                ('tin', models.CharField(blank=True, max_length=2, null=True, verbose_name='TIN Code')),
                ('is_union_territory', models.BooleanField(default=False)),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], db_index=True, default=1, help_text='1 = Active, 0 = Inactive')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'State Master',
                'verbose_name_plural': 'State Masters',
                'db_table': 'state_masters',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CustomerMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_type', models.CharField(choices=[('b2c', 'Retail Consumer (B2C)'), ('b2b', 'Registered Business (B2B)')], default='b2c', max_length=10)),
                ('name', models.CharField(max_length=150, verbose_name='Customer / Business Name')),
                ('phone', models.CharField(db_index=True, max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=120, null=True, verbose_name='Email Address')),
                ('gstin', models.CharField(blank=True, max_length=15, null=True, verbose_name='GSTIN Number')),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='PAN Number')),
                ('company_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Trade / Business Name')),
                ('billing_address', models.TextField(blank=True, null=True, verbose_name='Billing Address')),
                ('shipping_address', models.TextField(blank=True, null=True, verbose_name='Shipping Address')),
                ('city', models.CharField(blank=True, max_length=60, null=True, verbose_name='City')),
                ('pincode', models.CharField(blank=True, max_length=10, null=True, verbose_name='PIN Code')),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], db_index=True, default=1, help_text='1 = Active, 0 = Inactive')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers', to='catalogue.statemaster', verbose_name='State (Place of Supply)')),
            ],
            options={
                'verbose_name': 'Customer Master',
                'verbose_name_plural': 'Customer Masters',
                'db_table': 'customer_masters',
                'ordering': ['-created_at'],
            },
        ),
    ]
