# Generated by Django 6.1.1 on 2026-10-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_customermaster_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroupMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Age Group Name')),
                ('min_age', models.IntegerField(default=0, verbose_name='Minimum Age (Years)')),
                ('max_age', models.IntegerField(default=100, verbose_name='Maximum Age (Years)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], db_index=True, default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Age Group Master',
                'verbose_name_plural': 'Age Group Masters',
                'db_table': 'age_group_masters',
                'ordering': ['min_age'],
            },
        ),
        migrations.CreateModel(
            name='BrandMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Brand Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Brand Code')),
                ('logo_url', models.URLField(blank=True, max_length=300, null=True, verbose_name='Logo URL')),
                ('website', models.URLField(blank=True, max_length=255, null=True, verbose_name='Website')),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], db_index=True, default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Brand Master',
                'verbose_name_plural': 'Brand Masters',
                'db_table': 'brand_masters',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DesignMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Design / Pattern Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Design Code')),
                ('pattern_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Pattern Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], db_index=True, default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Design Master',
                'verbose_name_plural': 'Design Masters',
                'db_table': 'design_masters',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Material / Fabric Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Material Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('care_instructions', models.TextField(blank=True, null=True, verbose_name='Care Instructions')),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], db_index=True, default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Material Master',
                'verbose_name_plural': 'Material Masters',
                'db_table': 'material_masters',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SizeMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Size Name / Label')),
                ('code', models.CharField(max_length=50, verbose_name='Size Code')),
                ('category_type', models.CharField(default='Apparel', max_length=50, verbose_name='Category / Segment')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Sort Order')),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], db_index=True, default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Size Master',
                'verbose_name_plural': 'Size Masters',
                'db_table': 'size_masters',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
