# Generated by Django 6.1.1 on 2026-09-24 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Super Admin, Store Manager, Staff, Customer', max_length=100, unique=True)),
                ('code', models.CharField(db_index=True, help_text='Unique slug code e.g. SUPER_ADMIN, MANAGER, STAFF, CUSTOMER', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the role responsibilities', null=True)),
                ('is_superadmin', models.BooleanField(db_index=True, default=False, help_text='Designates full, unrestricted platform and configuration access', verbose_name='Is Superadmin')),
                ('capabilities', models.JSONField(blank=True, default=list, help_text="List of fine-grained capability keys e.g. ['products.view', 'orders.manage'] or ['*']")),
                ('access_policies', models.JSONField(blank=True, default=dict, help_text="Module/resource access policy map e.g. {'inventory': {'read': True, 'write': False}}")),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], db_index=True, default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, db_column='role_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.role', verbose_name='User Role'),
        ),
    ]
