# Generated by Django 6.1.1 on 2026-09-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_role_alter_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='access_policies',
        ),
        migrations.RemoveField(
            model_name='role',
            name='capabilities',
        ),
        migrations.RemoveField(
            model_name='role',
            name='code',
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, help_text='Role description', null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_superadmin',
            field=models.BooleanField(db_index=True, default=False, help_text='Designates whether this role is Super Admin', verbose_name='Is Superadmin'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(help_text='Role name (e.g. Super Admin, Store Manager, Staff, Customer)', max_length=100, unique=True),
        ),
    ]
