# Generated by Django 6.1.1 on 2026-09-30 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_remove_role_access_policies_remove_role_capabilities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, help_text='e.g. catalogue.categories.read', max_length=150, unique=True)),
                ('action', models.CharField(blank=True, db_index=True, help_text='e.g. read, create, update, delete', max_length=50, null=True)),
                ('label', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('module', models.CharField(db_index=True, default='core', max_length=50)),
                ('type', models.CharField(choices=[('ui', 'UI Visibility'), ('business', 'Business Gate')], default='ui', max_length=30)),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], db_index=True, default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Capability',
                'verbose_name_plural': 'Capabilities',
                'db_table': 'capabilities',
                'ordering': ['module', 'key'],
            },
        ),
        migrations.CreateModel(
            name='AccessPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(db_index=True, help_text='Target model e.g. users, category_master, sidebars', max_length=100)),
                ('actions', models.JSONField(default=list, help_text="e.g. ['read', 'create', 'update', 'delete', 'report']")),
                ('allow_access', models.JSONField(blank=True, default=dict, help_text="e.g. {'read': ['*'], 'create': ['name', 'rate']}")),
                ('forbidden_access', models.JSONField(blank=True, default=dict, help_text="e.g. {'read': ['password']}")),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='ABAC conditions')),
                ('registry', models.JSONField(blank=True, default=list)),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], db_index=True, default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, related_name='access_policies', to='users.role')),
            ],
            options={
                'verbose_name': 'Access Policy',
                'verbose_name_plural': 'Access Policies',
                'db_table': 'access_policies',
                'indexes': [models.Index(fields=['role_id', 'model_name', 'status'], name='access_poli_role_id_a10651_idx')],
                'unique_together': {('role', 'model_name')},
            },
        ),
        migrations.CreateModel(
            name='Sidebar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, help_text='e.g. LayoutDashboard, FolderTree, Package', max_length=100, null=True)),
                ('icon_package', models.CharField(default='lucide', max_length=50)),
                ('main_route', models.CharField(blank=True, db_index=True, help_text='e.g. /dashboard, /catalogue/categories', max_length=200, null=True)),
                ('visibility', models.CharField(choices=[('protected', 'Protected'), ('public', 'Public')], db_index=True, default='protected', max_length=20)),
                ('module_key', models.CharField(db_index=True, default='core', help_text='e.g. core, catalogue, users, orders', max_length=50)),
                ('has_children', models.BooleanField(default=False)),
                ('is_parent', models.BooleanField(default=False)),
                ('order', models.IntegerField(db_index=True, default=0)),
                ('badge', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'Active'), (0, 'Inactive')], db_index=True, default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capabilities', models.ManyToManyField(blank=True, related_name='sidebars', to='core.capability')),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.sidebar')),
            ],
            options={
                'verbose_name': 'Sidebar Item',
                'verbose_name_plural': 'Sidebar Items',
                'db_table': 'sidebars',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['status', 'order'], name='sidebars_status_91c8de_idx'), models.Index(fields=['parent_id', 'status'], name='sidebars_parent__10c061_idx'), models.Index(fields=['module_key', 'status'], name='sidebars_module__2afd25_idx')],
            },
        ),
    ]
