# Generated by Django 6.1.1 on 2026-10-04 12:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='description',
            field=models.TextField(blank=True, help_text='Human-readable activity summary', null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='method',
            field=models.CharField(blank=True, help_text='HTTP method e.g. GET, POST', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='module',
            field=models.CharField(blank=True, db_index=True, help_text='e.g. inventory, catalogue, users, core', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='path',
            field=models.CharField(blank=True, help_text='Request endpoint path', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='request_id',
            field=models.CharField(blank=True, db_index=True, help_text='Unique request correlation ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='status_code',
            field=models.IntegerField(blank=True, help_text='HTTP response status code', null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(db_index=True, help_text='CREATE, UPDATE, DELETE, LOGIN, LOGOUT, READ, EXPORT, PRINT', max_length=50),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['request_id'], name='audit_logs_request_298ea7_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'created_at'], name='audit_logs_action_391715_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['entity', 'created_at'], name='audit_logs_entity_a83371_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['module', 'created_at'], name='audit_logs_module_cb850a_idx'),
        ),
    ]
