# Generated by Django 6.1.1 on 2026-10-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auditlog_description_auditlog_method_auditlog_module_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(blank=True, db_index=True, default='CREATE', help_text='CREATE, UPDATE, DELETE, LOGIN, LOGOUT, READ, EXPORT, PRINT', max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity',
            field=models.CharField(blank=True, db_index=True, default='core', help_text='e.g. product, sale, customer, barcode, setting', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='module',
            field=models.CharField(blank=True, db_index=True, default='core', help_text='e.g. inventory, catalogue, users, core', max_length=100, null=True),
        ),
    ]
